name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
        matrix:
            node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: |
            pnpm run setup
            pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
